rmmod "ralink_gdma"
insmod "mtk_ralink_gdma.ko"
insmod "i2c_wm8960.ko"
insmod "snd-soc-mt76xx-i2s-ctl.ko"
insmod "snd-soc-mt76xx-i2s.ko"
insmod "snd-soc-ralink-i2s.ko"
insmod "snd-soc-mt76xx-pcm.ko"
insmod "snd-soc-wm8960.ko" "OUT2VOL=368" "INVOL=96"
insmod "snd-soc-mt76xx-machine.ko"
